const demos = [
  {
    name: 'Dashboard',
    screenshotLight: '/img/screenshots/home.png',
    screenshotDark: '/img/screenshots/home-dark.png',
    link: '/home.html',
    new: false,
  },
  {
    name: 'Transactions',
    screenshotLight: '/img/screenshots/transactions.png',
    screenshotDark: '/img/screenshots/transactions-dark.png',
    link: '/transactions.html',
    new: false,
  },
  {
    name: 'Payments',
    screenshotLight: '/img/screenshots/payments.png',
    screenshotDark: '/img/screenshots/payments-dark.png',
    link: '/payments.html',
    new: false,
  },
  {
    name: 'Cards',
    screenshotLight: '/img/screenshots/cards.png',
    screenshotDark: '/img/screenshots/cards-dark.png',
    link: '/cards.html',
    new: false,
  },
  {
    name: 'Credit request',
    screenshotLight: '/img/screenshots/credit.png',
    screenshotDark: '/img/screenshots/credit-dark.png',
    link: '/credit.html',
    new: false,
  },
  {
    name: 'Accounts',
    screenshotLight: '/img/screenshots/accounts.png',
    screenshotDark: '/img/screenshots/accounts-dark.png',
    link: '/accounts.html',
    new: false,
  },
  {
    name: 'Documents',
    screenshotLight: '/img/screenshots/documents.png',
    screenshotDark: '/img/screenshots/documents-dark.png',
    link: '/documents.html',
    new: false,
  },
  {
    name: 'Offers',
    screenshotLight: '/img/screenshots/offers.png',
    screenshotDark: '/img/screenshots/offers-dark.png',
    link: '/offers.html',
    new: false,
  },
  {
    name: 'Settings',
    screenshotLight: '/img/screenshots/settings.png',
    screenshotDark: '/img/screenshots/settings-dark.png',
    link: '/settings.html',
    new: false,
  },
  {
    name: 'Send money',
    screenshotLight: '/img/screenshots/payments-send.png',
    screenshotDark: '/img/screenshots/payments-send-dark.png',
    link: '/payments-send.html',
    new: false,
  },
  {
    name: 'Receive money',
    screenshotLight: '/img/screenshots/payments-receive.png',
    screenshotDark: '/img/screenshots/payments-receive-dark.png',
    link: '/payments-receive.html',
    new: false,
  },
  {
    name: 'Create card',
    screenshotLight: '/img/screenshots/cards-create.png',
    screenshotDark: '/img/screenshots/cards-create-dark.png',
    link: '/cards-create.html',
    new: false,
  },
  {
    name: 'Error 404',
    screenshotLight: '/img/screenshots/404.png',
    screenshotDark: '/img/screenshots/404-dark.png',
    link: '/404.html',
    new: false,
  },
  {
    name: 'Sign In',
    screenshotLight: '/img/screenshots/login.png',
    screenshotDark: '/img/screenshots/login-dark.png',
    link: '/login.html',
    new: false,
  },
  {
    name: 'Signup',
    screenshotLight: '/img/screenshots/signup.png',
    screenshotDark: '/img/screenshots/signup-dark.png',
    link: '/signup.html',
    new: false,
  },
  {
    name: 'Forgot password',
    screenshotLight: '/img/screenshots/forgot.png',
    screenshotDark: '/img/screenshots/forgot-dark.png',
    link: '/forgot.html',
    new: false,
  },
]

export function renderScreenshots() {
  return {
    screenshots: demos,
  }
}
