<?php

use App\Http\Controllers\Gateway\Authorize\ProcessController as AuthorizeProcessController;
use App\Http\Controllers\Gateway\BankPaymentProcessing;
use App\Http\Controllers\Gateway\Blockchain\ProcessController as BlockchainProcessController;
use App\Http\Controllers\Gateway\Cashmaal\ProcessController as CashmaalProcessController;
use App\Http\Controllers\Gateway\CoinbaseCommerce\ProcessController as CoinbaseCommerceProcessController;
use App\Http\Controllers\Gateway\Coingate\ProcessController as CoingateProcessController;
use App\Http\Controllers\Gateway\Coinpayments\ProcessController as CoinpaymentsProcessController;
use App\Http\Controllers\Gateway\CoinpaymentsFiat\ProcessController as CoinpaymentsFiatProcessController;
use App\Http\Controllers\Gateway\Instamojo\ProcessController as InstamojoProcessController;
use App\Http\Controllers\Gateway\Mollie\ProcessController as MollieProcessController;
use App\Http\Controllers\Gateway\NMI\ProcessController as NMIProcessController;
use App\Http\Controllers\Gateway\Payeer\ProcessController as PayeerProcessController;
use App\Http\Controllers\Gateway\Paypal\ProcessController as PaypalProcessController;
use App\Http\Controllers\Gateway\PaypalSdk\ProcessController;
use App\Http\Controllers\Gateway\Paystack\ProcessController as PaystackProcessController;
use App\Http\Controllers\Gateway\Paytm\ProcessController as PaytmProcessController;
use App\Http\Controllers\Gateway\PerfectMoney\ProcessController as PerfectMoneyProcessController;
use App\Http\Controllers\Gateway\Razorpay\ProcessController as RazorpayProcessController;
use App\Http\Controllers\Gateway\Skrill\ProcessController as SkrillProcessController;
use App\Http\Controllers\Gateway\Stripe\ProcessController as StripeProcessController;
use App\Http\Controllers\Gateway\StripeJs\ProcessController as StripeJsProcessController;
use App\Http\Controllers\Gateway\StripeV3\ProcessController as StripeV3ProcessController;
use App\Http\Controllers\Gateway\Voguepay\ProcessController as VoguepayProcessController;
use App\Http\Controllers\Gateway\WirelessPay\ProcessController as WirelessPay;
use Illuminate\Support\Facades\Route;

Route::post('paypal', [PaypalProcessController::class, 'ipn'])->name('Paypal');
Route::get('paypal-sdk', [ProcessController::class,'ipn'])->name('PaypalSdk');
Route::post('perfect-money', [PerfectMoneyProcessController::class,'ipn'])->name('PerfectMoney');
Route::post('stripe', [StripeProcessController::class,'ipn'])->name('Stripe');
Route::post('stripe-js',[StripeJsProcessController::class,'ipn'])->name('StripeJs');
Route::post('stripe-v3', [StripeV3ProcessController::class,'ipn'])->name('StripeV3');
Route::post('skrill', [SkrillProcessController::class,'ipn'])->name('Skrill');
Route::post('paytm', [PaytmProcessController::class,'ipn'])->name('Paytm');
Route::post('payeer', [PayeerProcessController::class,'ipn'])->name('Payeer');
Route::post('paystack', [PaystackProcessController::class,'ipn'])->name('Paystack');
Route::post('voguepay', [VoguepayProcessController::class,'ipn'])->name('Voguepay');
Route::get('flutterwave/{trx}/{type}', [ProcessController::class,'ipn'])->name('Flutterwave');
Route::post('razorpay', [RazorpayProcessController::class,'ipn'])->name('Razorpay');
Route::post('instamojo', [InstamojoProcessController::class,'ipn'])->name('Instamojo');
Route::get('blockchain', [BlockchainProcessController::class,'ipn'])->name('Blockchain');
Route::post('coinpayments', [CoinpaymentsProcessController::class,'ipn'])->name('Coinpayments');
Route::post('coinpayments-fiat', [CoinpaymentsFiatProcessController::class,'ipn'])->name('CoinpaymentsFiat');
Route::post('coingate', [CoingateProcessController::class,'ipn'])->name('Coingate');
Route::post('coinbase-commerce', [CoinbaseCommerceProcessController::class,'ipn'])->name('CoinbaseCommerce');
Route::get('mollie', [MollieProcessController::class,'ipn'])->name('Mollie');
Route::post('cashmaal', [CashmaalProcessController::class,'ipn'])->name('Cashmaal');
Route::post('mercado-pago', [\App\Http\Controllers\Gateway\MercadoPago\ProcessController::class,'ipn'])->name('MercadoPago');
Route::post('authorize', [AuthorizeProcessController::class,'ipn'])->name('Authorize');
Route::get('nmi', [NMIProcessController::class,'ipn'])->name('NMI');
Route::any('two-checkout', [ProcessController::class,'ipn'])->name('TwoCheckout');
Route::post('/village-boy-not-play-with-hacker-ensure-that-this-url-is-not-public-assessible',  [BankPaymentProcessing::class, 'webhook'])->name('webhook');
Route::get('wireless-pay',[WirelessPay::class, 'ipn'])->name('WirelessPay');
